# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66d0fac17fdb749736d8ab1d6fdffbb0b30b89fab73e20ec1a567c3fae472e8ec0c1ebb0e6f1c2cad81f4dd4237ce3adf2a21fc01474b5fa46e6336aeda51608

test:
  secret_key_base: 10081ae255992acb40e5e80c1bb6eaa4400e17e505ea087b0486d141398d8df02163f21ae0b4a7b4ad83454da82efda4f32ea0fbc0ec4f9466bb34f06eff80b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
